/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Verifica que el backend esté operativo.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Verifica que el backend y la base de datos estén operativos.
         */
        get: operations["readiness_check_health_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap User */
        post: operations["bootstrap_user_api_v1_users_me_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_api_v1_accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_v1_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/cash/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Income */
        post: operations["create_income_api_v1_cash_income_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash/expense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_v1_cash_expense_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        /** Delete Goal */
        delete: operations["delete_goal_api_v1_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Contribution */
        post: operations["create_contribution_api_v1_goals__goal_id__contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Obligations */
        get: operations["list_obligations_api_v1_obligations_get"];
        put?: never;
        /** Create Obligation */
        post: operations["create_obligation_api_v1_obligations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/obligations/{obligation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Obligation */
        get: operations["get_obligation_api_v1_obligations__obligation_id__get"];
        put?: never;
        post?: never;
        /** Delete Obligation */
        delete: operations["delete_obligation_api_v1_obligations__obligation_id__delete"];
        options?: never;
        head?: never;
        /** Update Obligation */
        patch: operations["update_obligation_api_v1_obligations__obligation_id__patch"];
        trace?: never;
    };
    "/api/v1/obligations/{obligation_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payment */
        post: operations["create_payment_api_v1_obligations__obligation_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_v1_credit_cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_api_v1_credit_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_api_v1_credit_cards__card_id__get"];
        put?: never;
        post?: never;
        /** Delete Card */
        delete: operations["delete_card_api_v1_credit_cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card */
        patch: operations["update_card_api_v1_credit_cards__card_id__patch"];
        trace?: never;
    };
    "/api/v1/credit/cards/{card_id}/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Purchase */
        post: operations["create_purchase_api_v1_credit_cards__card_id__purchases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credit/cards/{card_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payment */
        post: operations["create_payment_api_v1_credit_cards__card_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_v1_intelligence_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance */
        get: operations["get_balance_api_v1_intelligence_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/free-money": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Free Money */
        get: operations["get_free_money_api_v1_intelligence_free_money_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cashflow */
        get: operations["get_cashflow_api_v1_intelligence_cashflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/debt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Debt */
        get: operations["get_debt_api_v1_intelligence_debt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goals */
        get: operations["get_goals_api_v1_intelligence_goals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Obligations */
        get: operations["get_obligations_api_v1_intelligence_obligations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/credit-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Credit Cards */
        get: operations["get_credit_cards_api_v1_intelligence_credit_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Message
         * @description Endpoint conversacional unificado para MVP.
         */
        post: operations["process_message_api_v1_conversations_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBalanceRead */
        AccountBalanceRead: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Account Type */
            account_type: string;
            /** Currency */
            currency: string;
            /** Balance */
            balance: string;
        };
        /** AccountCreate */
        AccountCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["AccountType"];
            /**
             * Currency
             * @default COP
             */
            currency: string;
        };
        /** AccountRead */
        AccountRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            type: components["schemas"]["AccountType"];
            /** Balance */
            balance: string;
            /** Currency */
            currency: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "bank" | "wallet" | "cash" | "savings";
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name?: string | null;
        };
        /** CashExpenseCreate */
        CashExpenseCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Amount
             * @description Debe ser mayor estricto que 0
             */
            amount: number | string;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /** @default api */
            source: components["schemas"]["EventSource"];
        };
        /** CashIncomeCreate */
        CashIncomeCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Amount
             * @description Debe ser mayor estricto que 0
             */
            amount: number | string;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /** @default api */
            source: components["schemas"]["EventSource"];
        };
        /** CashOperationResult */
        CashOperationResult: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Balance After */
            balance_after: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Status
             * @description 'created' o 'idempotent_retry'
             */
            status: string;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"];
        };
        /** CategoryRead */
        CategoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Name */
            name: string;
            type: components["schemas"]["CategoryType"] | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * CategoryType
         * @enum {string}
         */
        CategoryType: "income" | "expense" | "credit_card" | "obligation" | "goal" | "transfer" | "system";
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
        };
        /**
         * ConversationalRequest
         * @description Payload de entrada del endpoint POST /api/v1/conversations/message
         */
        ConversationalRequest: {
            /** Message */
            message: string;
            /**
             * Channel
             * @default api
             * @enum {string}
             */
            channel: "api" | "pwa" | "whatsapp_future";
            /** External Message Id */
            external_message_id?: string | null;
            /** Pending Action Id */
            pending_action_id?: string | null;
        };
        /**
         * ConversationalResponse
         * @description Payload de salida del endpoint POST /api/v1/conversations/message
         */
        ConversationalResponse: {
            /** Response Text */
            response_text: string;
            /** Intent */
            intent: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "awaiting_clarification" | "awaiting_confirmation" | "cancelled" | "error";
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id: string;
            /** Pending Action Id */
            pending_action_id?: string | null;
            /** Structured Data */
            structured_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreditCardCreate */
        CreditCardCreate: {
            /** Name */
            name: string;
            /** Bank */
            bank: string;
            /** Credit Limit */
            credit_limit: number | string;
            /** Cutoff Day */
            cutoff_day: number;
            /** Due Day */
            due_day: number;
            /**
             * Currency
             * @default COP
             */
            currency: string;
        };
        /** CreditCardPaymentCreate */
        CreditCardPaymentCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Amount */
            amount: number | string;
        };
        /** CreditCardPaymentResult */
        CreditCardPaymentResult: {
            /** Status */
            status: string;
            /** Event Id */
            event_id?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
            /** Amount */
            amount: string;
            /** Estimated Current Debt */
            estimated_current_debt: string;
            /** Account Balance */
            account_balance: string;
        };
        /** CreditCardPurchaseCreate */
        CreditCardPurchaseCreate: {
            /** Amount */
            amount: number | string;
            /** Category Id */
            category_id?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Installments Total
             * @default 1
             */
            installments_total: number;
        };
        /** CreditCardPurchaseResult */
        CreditCardPurchaseResult: {
            /** Status */
            status: string;
            /** Event Id */
            event_id?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
            /** Amount */
            amount: string;
            /** Estimated Current Debt */
            estimated_current_debt: string;
            /** Estimated Available Credit */
            estimated_available_credit: string;
        };
        /** CreditCardRead */
        CreditCardRead: {
            /** Name */
            name: string;
            /** Bank */
            bank: string;
            /** Credit Limit */
            credit_limit: string;
            /** Cutoff Day */
            cutoff_day: number;
            /** Due Day */
            due_day: number;
            /**
             * Currency
             * @default COP
             */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Estimated Current Debt
             * @default 0.00
             */
            estimated_current_debt: string;
            /**
             * Monthly Cc Payment
             * @default 0.00
             */
            monthly_cc_payment: string;
            /** Estimated Available Credit */
            readonly estimated_available_credit: string;
        };
        /** CreditCardUpdate */
        CreditCardUpdate: {
            /** Name */
            name?: string | null;
            /** Bank */
            bank?: string | null;
            /** Credit Limit */
            credit_limit?: number | string | null;
            /** Cutoff Day */
            cutoff_day?: number | null;
            /** Due Day */
            due_day?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * EventSource
         * @enum {string}
         */
        EventSource: "api" | "pwa" | "manual" | "system";
        /** FreeMoneyRead */
        FreeMoneyRead: {
            /** Available Real */
            available_real: string;
            /** Minus Pending Obligations */
            minus_pending_obligations: string;
            /** Minus Goals Required */
            minus_goals_required: string;
            /** Minus Credit Cards Required Payment */
            minus_credit_cards_required_payment: string;
            /** Free Money Result */
            free_money_result: string;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** GoalContributionCreate */
        GoalContributionCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Amount */
            amount: number | string;
        };
        /** GoalContributionResult */
        GoalContributionResult: {
            /** Contribution Id */
            contribution_id: string | null;
            /** Event Id */
            event_id: string | null;
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Goal Current Amount */
            goal_current_amount: string;
            /** Progress Percentage */
            progress_percentage: string | null;
            /** Status */
            status: string;
        };
        /** GoalCreate */
        GoalCreate: {
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: number | string;
            /** Target Date */
            target_date?: string | null;
        };
        /** GoalRead */
        GoalRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: string;
            /** Current Amount */
            current_amount: string;
            /** Target Date */
            target_date: string | null;
            /** Status */
            status: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Remaining Amount */
            readonly remaining_amount: string;
            /** Progress Percentage */
            readonly progress_percentage: string;
            /** Monthly Required */
            readonly monthly_required: string | null;
            /** Daily Required */
            readonly daily_required: string | null;
        };
        /** GoalUpdate */
        GoalUpdate: {
            /** Name */
            name?: string | null;
            /** Target Amount */
            target_amount?: number | string | null;
            /** Target Date */
            target_date?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Respuesta del endpoint de salud.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** IntelligenceBalanceRead */
        IntelligenceBalanceRead: {
            /** Total Available Real */
            total_available_real: string;
            /** Accounts */
            accounts: components["schemas"]["AccountBalanceRead"][];
            /** Currency */
            currency: string;
        };
        /** IntelligenceCashflowRead */
        IntelligenceCashflowRead: {
            /** Income */
            income: string;
            /** Expense */
            expense: string;
            /** Cash Consumption Outflow */
            cash_consumption_outflow: string;
            /** Credit Card Consumption Committed */
            credit_card_consumption_committed: string;
            /** Total Consumption Committed */
            total_consumption_committed: string;
            /** Committed Outflow */
            committed_outflow: string;
            /** Wealth Allocation */
            wealth_allocation: string;
            /** Debt Service */
            debt_service: string;
            /** Net Cashflow */
            net_cashflow: string;
            /** Period */
            period: string;
        };
        /** IntelligenceCreditCardRead */
        IntelligenceCreditCardRead: {
            /**
             * Credit Card Id
             * Format: uuid
             */
            credit_card_id: string;
            /** Credit Card Name */
            credit_card_name: string;
            /** Credit Limit */
            credit_limit: string | null;
            /** Estimated Current Debt */
            estimated_current_debt: string;
            /** Estimated Available Credit */
            estimated_available_credit: string | null;
            /** Monthly Cc Payment */
            monthly_cc_payment: string;
            /** Cutoff Day */
            cutoff_day: number | null;
            /** Due Day */
            due_day: number | null;
        };
        /** IntelligenceDebtRead */
        IntelligenceDebtRead: {
            /** Total Estimated Credit Card Debt */
            total_estimated_credit_card_debt: string;
            /** Total Monthly Cc Payment */
            total_monthly_cc_payment: string;
            /** Credit Cards */
            credit_cards: components["schemas"]["IntelligenceCreditCardRead"][];
            /** Pending Commitments */
            pending_commitments: {
                [key: string]: unknown;
            }[];
        };
        /** IntelligenceGoalRead */
        IntelligenceGoalRead: {
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Name */
            name: string;
            /** Target Amount */
            target_amount: string;
            /** Current Amount */
            current_amount: string;
            /** Progress Percentage */
            progress_percentage: string;
            /** Remaining Amount */
            remaining_amount: string;
            /** Monthly Required */
            monthly_required: string | null;
            /** Daily Required */
            daily_required: string | null;
            /** Remaining Required This Period */
            remaining_required_this_period: string;
            /** Status */
            status: string;
        };
        /** IntelligenceObligationRead */
        IntelligenceObligationRead: {
            /**
             * Obligation Id
             * Format: uuid
             */
            obligation_id: string;
            /** Name */
            name: string;
            /** Amount */
            amount: string;
            /** Due Day */
            due_day: number | null;
            /** Frequency */
            frequency: string;
            /** Is Pending */
            is_pending: boolean;
        };
        /** IntelligenceSnapshotRead */
        IntelligenceSnapshotRead: {
            /** Available Real */
            available_real: string;
            /** Safe Money */
            safe_money: string;
            /** Free Money */
            free_money: string;
            /** Total Income Current Month */
            total_income_current_month: string;
            /** Cash Consumption Outflow */
            cash_consumption_outflow: string;
            /** Credit Card Consumption Committed */
            credit_card_consumption_committed: string;
            /** Total Consumption Committed */
            total_consumption_committed: string;
            /** Committed Outflow Current Month */
            committed_outflow_current_month: string;
            /** Wealth Allocation Current Month */
            wealth_allocation_current_month: string;
            /** Pending Obligations Total */
            pending_obligations_total: string;
            /** Goals Required This Period */
            goals_required_this_period: string;
            /** Credit Cards Required Payment */
            credit_cards_required_payment: string;
            /** Total Credit Card Debt */
            total_credit_card_debt: string;
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
        };
        /** ObligationCreate */
        ObligationCreate: {
            /** Name */
            name: string;
            /** Amount */
            amount: number | string;
            /** Due Day */
            due_day?: number | null;
            /** Frequency */
            frequency?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ObligationPaymentCreate */
        ObligationPaymentCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Amount */
            amount: number | string;
        };
        /** ObligationPaymentResult */
        ObligationPaymentResult: {
            /** Payment Id */
            payment_id: string | null;
            /** Event Id */
            event_id: string | null;
            /** Amount */
            amount: string;
            /** Balance After */
            balance_after: string;
            /** Status */
            status: string;
        };
        /** ObligationRead */
        ObligationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Amount */
            amount: string;
            /** Due Day */
            due_day: number | null;
            /** Frequency */
            frequency: string | null;
            /** Is Active */
            is_active: boolean;
            /** Category Id */
            category_id: string | null;
            /** Currency */
            currency: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ObligationUpdate */
        ObligationUpdate: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Due Day */
            due_day?: number | null;
            /** Frequency */
            frequency?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** UserOnboardingRequest */
        UserOnboardingRequest: {
            /** Name */
            name?: string | null;
            /**
             * Timezone
             * @default America/Bogota
             */
            timezone: string;
            /**
             * Currency
             * @default COP
             */
            currency: string;
        };
        /** UserOnboardingResponse */
        UserOnboardingResponse: {
            /** Created */
            created: boolean;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            profile: components["schemas"]["UserRead"];
            /** Next Step */
            next_step: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Timezone */
            timezone: string;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_health_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    bootstrap_user_api_v1_users_me_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserOnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"][];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_api_v1_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_v1_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_income_api_v1_cash_income_post: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único para identificar la transacción de negocio */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashIncomeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashOperationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_cash_expense_post: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID único para identificar la transacción de negocio */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashOperationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"][];
                };
            };
        };
    };
    create_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_api_v1_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contribution_api_v1_goals__goal_id__contributions_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalContributionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalContributionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_obligations_api_v1_obligations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationRead"][];
                };
            };
        };
    };
    create_obligation_api_v1_obligations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObligationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_obligation_api_v1_obligations__obligation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_obligation_api_v1_obligations__obligation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_obligation_api_v1_obligations__obligation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObligationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_api_v1_obligations__obligation_id__payments_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                obligation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObligationPaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationPaymentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_v1_credit_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardRead"][];
                };
            };
        };
    };
    create_card_api_v1_credit_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_api_v1_credit_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_api_v1_credit_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_api_v1_credit_cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_purchase_api_v1_credit_cards__card_id__purchases_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCardPurchaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardPurchaseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_api_v1_credit_cards__card_id__payments_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditCardPaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditCardPaymentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_v1_intelligence_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceSnapshotRead"];
                };
            };
        };
    };
    get_balance_api_v1_intelligence_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceBalanceRead"];
                };
            };
        };
    };
    get_free_money_api_v1_intelligence_free_money_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeMoneyRead"];
                };
            };
        };
    };
    get_cashflow_api_v1_intelligence_cashflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceCashflowRead"];
                };
            };
        };
    };
    get_debt_api_v1_intelligence_debt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceDebtRead"];
                };
            };
        };
    };
    get_goals_api_v1_intelligence_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceGoalRead"][];
                };
            };
        };
    };
    get_obligations_api_v1_intelligence_obligations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceObligationRead"][];
                };
            };
        };
    };
    get_credit_cards_api_v1_intelligence_credit_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceCreditCardRead"][];
                };
            };
        };
    };
    process_message_api_v1_conversations_message_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Trace-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
